### ISSUE TITLE
[Bug] Character won't Equip Sword Item 3

### ISSUE THREAD

**Issue by HenrickTheBull** [CryptidNeons/ITCN#2]
Attempted to equip sword item 3 to character. Bugged out and crashed to desktop!

[Insert Image here]

[Insert Details Here]

**Comment by CryptidNeons** [comment]
sux 2 b u

**Comment by CryptidNeons** [comment]
Fixed in V 0.00.1!

**Comment by ashtif** [comment]
gay bull can't equip sword
